### ISSUE TITLE
Not working in chrome with a surface pro

### ISSUE THREAD

**Issue by mauriciabad** [devinhunt/colordot#2]
Maybe due to its touchscreen. But it works in Edge.

**Comment by devinhunt** [comment]
Thanks for the issue. This was due to colordot using rejected gesture API (apple only now). I've updated the site and touch controls (move and pinch) should now allow control the app. 

Let me know if that is working on your surface in any browser.

**Comment by devinhunt** [comment]
I'll close this issue for now. Do reopen with new feedback if the problem persists.
